### ISSUE TITLE
No such file "**/model.npz"

### ISSUE THREAD

**Issue by catalyster** [hanxingjian/GroundLink#3]
In preprocess.ipynb
```
# load model file to remove pelvis offset from SMPL-X model
modelpath = '../Data/smplx/' + str(mocap["gender"])
# modelpath = '../../../Data/QTM_SOMA_MOSH/support_files/smplx/' + str(mocap["gender"])
modelfile = os.path.join(modelpath, 'model.npz')
modeldata = np.load(modelfile, allow_pickle=True)
pelvis_offset = modeldata['J'][0]
```
Sorry, I do not find the file named "**/model.npz" in **modelpath**. Did you forget to upload it？Looking forward to your reply.

**Comment by hanxingjian** [comment]
> In preprocess.ipynb
> 
> ```
> # load model file to remove pelvis offset from SMPL-X model
> modelpath = '../Data/smplx/' + str(mocap["gender"])
> # modelpath = '../../../Data/QTM_SOMA_MOSH/support_files/smplx/' + str(mocap["gender"])
> modelfile = os.path.join(modelpath, 'model.npz')
> modeldata = np.load(modelfile, allow_pickle=True)
> pelvis_offset = modeldata['J'][0]
> ```
> 
> Sorry, I do not find the file named "**/model.npz" in **modelpath**. Did you forget to upload it？Looking forward to your reply.

Hi!

Due to licensing with SMPL-X, please register and download corresponding models from this page: [https://smpl-x.is.tue.mpg.de/download.php](url). I believe I had the second option under **SMPL-X Model** from the Download page. Please let me know if there is further issue.

Once you have the model, you may follow the instruction and place them into proper model folder for the SMPL models. 

XJ
